[theme]
base = "light"
primaryColor = "#087f70"
backgroundColor = "#f4f6f2"
secondaryBackgroundColor = "#edf2ee"
textColor = "#17231f"
font = "sans serif"

[server]
maxUploadSize = 25

[browser]
gatherUsageStats = false
